logging:
  level:
    org.springframework.data.redis: trace
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  profiles:
    include: common
    active: local
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
#    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
#  sql:
#    init:
#      mode: embedded
#      data-locations: classpath*:db/h2/data.sql
