spring:
  profiles:
    include: common
    active: dev
  datasource:
    url: jdbc:mysql://knockknockdb.ce0eox1y1obm.us-east-1.rds.amazonaws.com:3306/knockdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${RDS_PW}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create