jwt:
  secret: ${JWT_SECRET_KEY}
  expirationMs: 3600000
token:
  expiration:
    access: 86400000
    refresh: 31536000000
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            scope: email, profile
          kakao:
            client-id: fdfae2918a363efc5fad0a501f3dcd55
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope: profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: 4othersofficial@gmail.com
    password: ${SMTP_CREDENTIALS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
cors:
  allowed-origins: 'http://www.knockknockofficial.shop:8080'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris: http://localhost:8080
    #프론트 페이지만들어지면 여기다가 넣기
