version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/action/back/KnockKnock
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/empty_script.sh
      timeout: 3000
      runas: root
  DownloadBundle:
    - location: scripts/empty_script.sh
      timeout: 3000
      runas: root
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 3000
      runas: root
  Install:
    - location: scripts/empty_script.sh
      timeout: 3000
      runas: root
  AfterInstall:
    - location: scripts/initialize.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 3000
      runas: root
  ValidateService:
    - location: scripts/empty_script.sh
      timeout: 3000
      runas: root
