# APP
FROM openjdk:11-jdk
WORKDIR /app

# 빌더 이미지에서 jar 파일만 복사
COPY /build/libs/KnockKnock-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

# root 대신 nobody 권한으로 실행
USER nobody
ENTRYPOINT [ \
   "java", \
   "-Dspring.profiles.active=dev",\
   "-Djava.security.egd=file:/dev/./urandom", \
   "-Dsun.net.inetaddr.ttl=0", \
   "-jar", \
   "app.jar" \
]